package studio.sinya.jp.demo_gridviewphotowall.bean;

/**
 * Created by SinyaKoizumi on 2015/10/17.
 */
public class ImageBean {

    private final static String url = "http://10.0.2.2:8080/QQJY/data/images/";
    private final static String name = ".png";
    /**
     * 图片地址
     */
    public final static String[] imageUrl = new String[]{
            url + 1 + name,
            url + 2 + name,
            url + 3 + name,
            url + 4 + name,
            url + 5 + name,
            url + 6 + name,
            url + 7 + name,
            url + 8 + name,
            url + 9 + name,
            url + 10 + name,
            url + 11 + name,
            url + 12 + name,
            url + 13 + name,
            url + 14 + name,
            url + 15 + name,
            url + 16 + name,
            url + 17 + name,
            url + 18 + name,
            url + 19 + name,
            url + 20 + name,
            url + 21 + name,
            url + 22 + name,
            url + 23 + name,
            url + 24 + name,
            url + 25 + name,
            url + 26 + name,
            url + 27 + name,
            url + 28 + name,
            url + 29 + name,
            url + 30 + name,
            url + 31 + name,
            url + 32 + name,
            url + 33 + name,
            url + 34 + name,
            url + 35 + name,
            url + 36 + name,
            url + 37 + name,
            url + 38 + name,
            url + 39 + name,
            url + 40 + name,
            url + 41 + name,
            url + 42 + name,
            url + 43 + name,
            url + 44 + name,
            url + 45 + name,
            url + 46 + name,
            url + 47 + name,
            url + 48 + name,
            url + 49 + name,
            url + 50 + name,
            url + 51 + name,
            url + 52 + name,
            url + 53 + name,
            url + 54 + name,
            url + 55 + name,
            url + 56 + name,
            url + 57 + name,
            url + 58 + name,
            url + 59 + name,
            url + 60 + name,
            url + 61 + name,
            url + 62 + name,
            url + 63 + name,
            url + 64 + name,
            url + 65 + name,
            url + 66 + name,
            url + 67 + name,
            url + 68 + name,
            url + 69 + name,
            url + 70 + name,
            url + 71 + name,
            url + 72 + name,
            url + 73 + name,
            url + 74 + name,
            url + 75 + name,
            url + 76 + name,
            url + 77 + name,
            url + 78 + name,
            url + 79 + name,
            url + 80 + name,
            url + 81 + name,
            url + 82 + name,
            url + 83 + name,
            url + 84 + name,
            url + 85 + name,
            url + 86 + name,
            url + 87 + name,
            url + 88 + name,
            url + 89 + name,
            url + 90 + name,

    };


}
